///////////////////////////////////////////////////////////////////////////////
// Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.     //
// You may override this file locally, but any changes will be overwritten  //
// the next time CI is regenerated. Permanent fixes must be made inside:    //
// RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                   //
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Linq;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Main build script materialized into the sample project. It builds the player with ALL and ONLY the enabled
/// scenes; to build a different scene set, branch off in the sample repo and clone from that branch.
/// </summary>
public class BuilderScripts : MonoBehaviour
{
    static string[] GetEnabledScenes()
    {
        return EditorBuildSettings.scenes
            .Where(scene => scene.enabled)
            .Select(scene => scene.path)
            .ToArray();
    }

    static void BuildPlayer(BuildConfig config)
    {
        PlayerSettings.SetScriptingBackend(config.NamedBuildTarget, config.ScriptingBackend);

        if (config.GraphicsApis != null && config.GraphicsApis.Length > 0)
        {
            PlayerSettings.SetUseDefaultGraphicsAPIs(config.BuildTarget, false);
            PlayerSettings.SetGraphicsAPIs(config.BuildTarget, config.GraphicsApis);
        }

        if (config.ApplicationId != null)
            PlayerSettings.SetApplicationIdentifier(config.NamedBuildTarget, config.ApplicationId);

        if (config.Architecture.HasValue)
            PlayerSettings.SetArchitecture(config.NamedBuildTarget, config.Architecture.Value);

        AssetDatabase.SaveAssets();

        var buildOptions = new BuildPlayerOptions
        {
            locationPathName = config.OutputPath,
            target = config.BuildTarget,
            options = BuildOptions.Development,
            scenes = GetEnabledScenes()
        };

        BuildPipeline.BuildPlayer(buildOptions);
    }

    struct BuildConfig
    {
        public NamedBuildTarget NamedBuildTarget;
        public ScriptingImplementation ScriptingBackend;
        public BuildTarget BuildTarget;
        public GraphicsDeviceType[] GraphicsApis;
        public string OutputPath;
        // Not 'string?': materialized into projects with nullable disabled, where that annotation is a hard CS8632 error.
        public string ApplicationId;
        public int? Architecture;
    }

    [MenuItem("Tools/Builder/Build Development Windows Il2cpp")]
    static void BuildWinIl2cpp() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Standalone,
        ScriptingBackend = ScriptingImplementation.IL2CPP,
        BuildTarget = BuildTarget.StandaloneWindows64,
        GraphicsApis = new[] { GraphicsDeviceType.Vulkan, GraphicsDeviceType.Direct3D11, GraphicsDeviceType.Direct3D12 },
        OutputPath = "./build/Windows_Il2cpp/PlaytestBuild.exe"
    });

    [MenuItem("Tools/Builder/Build Development Windows Mono")]
    static void BuildWinMono() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Standalone,
        ScriptingBackend = ScriptingImplementation.Mono2x,
        BuildTarget = BuildTarget.StandaloneWindows64,
        GraphicsApis = new[] { GraphicsDeviceType.Vulkan, GraphicsDeviceType.Direct3D11, GraphicsDeviceType.Direct3D12 },
        OutputPath = "./build/Windows_Mono/PlaytestBuild.exe"
    });

    [MenuItem("Tools/Builder/Build Development Mac Mono")]
    static void BuildMacMono() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Standalone,
        ScriptingBackend = ScriptingImplementation.Mono2x,
        BuildTarget = BuildTarget.StandaloneOSX,
        GraphicsApis = new[] { GraphicsDeviceType.Metal },
        OutputPath = "./build/macOS_Mono/PlaytestBuild.app"
    });

    [MenuItem("Tools/Builder/Build Development Mac Il2cpp")]
    static void BuildMacIl2cpp() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Standalone,
        ScriptingBackend = ScriptingImplementation.IL2CPP,
        BuildTarget = BuildTarget.StandaloneOSX,
        GraphicsApis = new[] { GraphicsDeviceType.Metal },
        OutputPath = "./build/macOS_Il2cpp/PlaytestBuild.app"
    });

    [MenuItem("Tools/Builder/Build Development Android Il2cpp")]
    static void BuildAndroidIl2cpp() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Android,
        ScriptingBackend = ScriptingImplementation.IL2CPP,
        BuildTarget = BuildTarget.Android,
        GraphicsApis = new[] { GraphicsDeviceType.Vulkan },
        OutputPath = "./build/Android_Il2cpp_Vulkan/PlaytestBuild.apk",
        ApplicationId = "com.UnityTestRunner.UnityTestRunner",
        Architecture = 1
    });

#if UNITY_6000_6_OR_NEWER
    // ScriptingImplementation.CoreCLR is marked [Obsolete] ("work in progress"), so suppress CS0618 to compile under warnings-as-errors.
#pragma warning disable CS0618
    static ScriptingImplementation CoreClrBackend => ScriptingImplementation.CoreCLR;
#pragma warning restore CS0618

    [MenuItem("Tools/Builder/Build Development Windows CoreCLR")]
    static void BuildWinCoreClr() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Standalone,
        ScriptingBackend = CoreClrBackend,
        BuildTarget = BuildTarget.StandaloneWindows64,
        GraphicsApis = new[] { GraphicsDeviceType.Vulkan, GraphicsDeviceType.Direct3D11, GraphicsDeviceType.Direct3D12 },
        OutputPath = "./build/Windows_CoreClr/PlaytestBuild.exe"
    });

    [MenuItem("Tools/Builder/Build Development Mac CoreCLR")]
    static void BuildMacCoreClr() => BuildPlayer(new BuildConfig
    {
        NamedBuildTarget = NamedBuildTarget.Standalone,
        ScriptingBackend = CoreClrBackend,
        BuildTarget = BuildTarget.StandaloneOSX,
        GraphicsApis = new[] { GraphicsDeviceType.Metal },
        OutputPath = "./build/macOS_CoreClr/PlaytestBuild.app"
    });

    [MenuItem("Tools/Builder/Build Development Android CoreCLR")]
    static void BuildAndroidCoreClr()
    {
        // CoreCLR on Android is 64-bit only; ARMv7 (32-bit) is unsupported, so force ARM64.
        PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARM64;
        BuildPlayer(new BuildConfig
        {
            NamedBuildTarget = NamedBuildTarget.Android,
            ScriptingBackend = CoreClrBackend,
            BuildTarget = BuildTarget.Android,
            GraphicsApis = new[] { GraphicsDeviceType.Vulkan },
            OutputPath = "./build/Android_CoreClr/PlaytestBuild.apk",
            ApplicationId = "com.UnityTestRunner.UnityTestRunner"
        });
    }
#endif
}
