###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Extends the job's own (source) sparse checkout to include the local tested-package folders named at
runtime by LOCAL_TESTED_PACKAGES_NAMES.

The generated rules file materializes a baseline set at checkout time, but the packages to test are read
from the environment here so that a package added (or changed) via the LOCAL_TESTED_PACKAGES_NAMES trigger
variable is checked out on demand rather than failing because it was absent from the pre-baked rules. Adding
a path that does not exist in the repository materializes nothing and is not an error; validate_params.py is
what reports a genuinely missing package.
"""

import argparse
import os
import subprocess
import sys

from package_parsing import parse_package_names

ENV_LOCAL_TESTED_PACKAGES_NAMES = "LOCAL_TESTED_PACKAGES_NAMES"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Add local tested-package folders to the source repo's sparse checkout."
    )
    parser.add_argument("--source-dir", required=True, help="Absolute path to the job's source checkout (git repo root).")
    parser.add_argument(
        "--local-tested-packages-path",
        required=True,
        help="Repo-relative base directory containing the local packages (e.g. 'Packages').",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    package_names = parse_package_names(os.environ.get(ENV_LOCAL_TESTED_PACKAGES_NAMES, ""))
    if not package_names:
        print(f"[INFO] {ENV_LOCAL_TESTED_PACKAGES_NAMES} is empty; no source paths to add.")
        return

    base_path = args.local_tested_packages_path.strip().replace("\\", "/").strip("/")
    paths = [f"{base_path}/{name}" for name in package_names]

    result = subprocess.run(
        ["git", "-C", args.source_dir, "sparse-checkout", "add", *paths],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False,
    )
    if result.returncode != 0:
        print(f"Error extending source sparse checkout: {result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)

    print(f"[INFO] Added to source sparse checkout: {paths}")


if __name__ == "__main__":
    main()
