###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Helper script that determines the appropriate BuilderScripts method and 
runs Unity with the correct parameters.
"""

import argparse
import os
import subprocess
import sys

BUILD_CONFIGS = {
    ("win64", "il2cpp"): {"method": "BuilderScripts.BuildWinIl2cpp", "buildTarget": "win64"},
    ("win64", "mono"): {"method": "BuilderScripts.BuildWinMono", "buildTarget": "win64"},
    ("win64", "coreclr"): {"method": "BuilderScripts.BuildWinCoreClr", "buildTarget": "win64"},
    ("mac", "il2cpp"): {"method": "BuilderScripts.BuildMacIl2cpp", "buildTarget": "osx"},
    ("mac", "mono"): {"method": "BuilderScripts.BuildMacMono", "buildTarget": "osx"},
    ("mac", "coreclr"): {"method": "BuilderScripts.BuildMacCoreClr", "buildTarget": "osx"},
    ("android", "il2cpp"): {"method": "BuilderScripts.BuildAndroidIl2cpp", "buildTarget": "android"},
    ("android", "coreclr"): {"method": "BuilderScripts.BuildAndroidCoreClr", "buildTarget": "android"},
}


def resolve_backend():
    return os.environ.get("SCRIPTING_BACKEND_(IL2CPP_MONO_CORECLR)", "").lower()

def execute_unity_build(project_path, unity_path):
    platform = os.environ.get("PLATFORM_(WIN64_MAC_ANDROID)", "").lower()
    backend = resolve_backend()
    config = BUILD_CONFIGS.get((platform, backend))
    if not config:
        print(f"ERROR: Invalid combination: platform={platform}, backend={backend}", file=sys.stderr)
        sys.exit(1)

    cmd = [
        unity_path,
        "-projectPath",
        project_path,
        "-buildTarget",
        config["buildTarget"],
        "-executeMethod",
        config["method"],
        "-batchmode",
        "-logFile",
        "./artifacts/UnityLog.txt",
        "-automated",
        "-crash-report-folder",
        "./artifacts/CrashArtifacts",
        "-quit",
    ]
    result = subprocess.run(cmd, check=False)
    sys.exit(result.returncode)


def main():
    parser = argparse.ArgumentParser(description="Execute Unity build command.")
    parser.add_argument("--project-path", required=True, help="Path to Unity project.")
    parser.add_argument("--unity-path", default="C:/TestingEditor/Unity.exe", help="Path to Unity executable.")
    args = parser.parse_args()
    execute_unity_build(args.project_path, args.unity_path)


if __name__ == "__main__":
    main()
