###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Updates the cloned project's manifest.json to point tested packages at local file: sources, so the
changes on the current branch are exercised against the sample project.

!!! IMPORTANT !!! — UPM embedded package priority:
Any package folder placed directly inside the project's Packages/ directory is treated as an
embedded package and takes the absolute highest priority in UPM dependency resolution.

To work around this, the script scans the Packages/ directory of the cloned project and removes any
embedded package whose package.json declares a name matching a target package, before writing the
local file: reference into the manifest.
"""

import argparse
import json
import os
import shutil
import sys

from package_parsing import parse_package_names

SEPARATOR = "=" * 80
ENV_LOCAL_TESTED_PACKAGES_NAMES = "LOCAL_TESTED_PACKAGES_NAMES"


def parse_args():
    parser = argparse.ArgumentParser(description="Update a Unity project manifest to use local package versions.")
    parser.add_argument("--manifest-path", required=True, help="Absolute path to project manifest.json file.")
    parser.add_argument(
        "--local-tested-packages-path",
        required=True,
        help="Absolute path to the local packages root directory (e.g. the source dir's Packages folder).",
    )
    return parser.parse_args()


def remove_embedded_package(packages_dir, package_name):
    """
    Scans subfolders of packages_dir and removes any folder whose package.json
    declares a 'name' matching package_name.
    """
    if not os.path.isdir(packages_dir):
        return

    for entry in os.scandir(packages_dir):
        if not entry.is_dir():
            continue
        package_json_path = os.path.join(entry.path, "package.json")
        if not os.path.isfile(package_json_path):
            continue
        try:
            with open(package_json_path, "r", encoding="utf-8") as f:
                name = json.load(f).get("name", "")
        except Exception:
            continue

        if name == package_name:
            shutil.rmtree(entry.path)
            print(f"[INFO] Removed embedded package '{package_name}' from '{entry.path}'")
            return


def update_manifest(manifest_data, package_name, local_packages_root):
    old_value = manifest_data.get("dependencies", {}).get(package_name, "<not present>")
    local_package_path = os.path.join(local_packages_root, package_name)
    local_path_normalized = local_package_path.replace(os.sep, "/")
    manifest_data.setdefault("dependencies", {})[package_name] = f"file:{local_path_normalized}"
    return old_value, f"file:{local_path_normalized}"


def print_summary(manifest_data, substitutions):
    print()
    print(SEPARATOR)
    print("TARGET PACKAGE SUBSTITUTION")
    print(SEPARATOR)
    for substitution in substitutions:
        print(f"Package: {substitution['package_name']}")
        print(f"  Old value: {substitution['old_value']}")
        print(f"  New value: {substitution['new_value']}")
        local_version = substitution["local_version"] or "<unknown>"
        print(f"Verified local '{substitution['package_name']}' version is: {local_version}")
        print()
    print(SEPARATOR)
    print("FINAL MANIFEST CONTENT")
    print(SEPARATOR)
    dependencies = manifest_data.get("dependencies", {})
    for dep_name, dep_value in sorted(dependencies.items()):
        print(f"  {dep_name}: {dep_value}")
    print(SEPARATOR)
    print()


def get_package_version(package_path):
    package_json_path = os.path.join(package_path, "package.json")
    try:
        with open(package_json_path, "r", encoding="utf-8") as f:
            return json.load(f).get("version", "N/A")
    except Exception:
        return None


def main():
    args = parse_args()

    try:
        package_names = parse_package_names(os.environ.get(ENV_LOCAL_TESTED_PACKAGES_NAMES, ""))
        # Clearing the variable at trigger time opts out of substitution; leave the manifest untouched (plain build).
        if not package_names:
            print(f"[INFO] {ENV_LOCAL_TESTED_PACKAGES_NAMES} is empty; skipping local package substitution.")
            return

        with open(args.manifest_path, "r", encoding="utf-8") as manifest_file:
            manifest_data = json.load(manifest_file)

        packages_dir = os.path.dirname(args.manifest_path)

        substitutions = []
        for package_name in package_names:
            remove_embedded_package(packages_dir, package_name)

            old_value, new_value = update_manifest(
                manifest_data,
                package_name,
                args.local_tested_packages_path,
            )
            local_package_path = os.path.join(args.local_tested_packages_path, package_name)
            local_version = get_package_version(local_package_path)
            substitutions.append(
                {
                    "package_name": package_name,
                    "old_value": old_value,
                    "new_value": new_value,
                    "local_version": local_version,
                }
            )

        with open(args.manifest_path, "w", encoding="utf-8", newline="\n") as manifest_file:
            json.dump(manifest_data, manifest_file, indent=4)

        print_summary(manifest_data, substitutions)
    except Exception as error:
        print(f"Error updating manifest: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
