###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Shared parsing for the LOCAL_TESTED_PACKAGES_NAMES variable, so every build-automation script splits it the
same way. Package names may be separated by commas, semicolons, and/or whitespace in any combination, so
values entered as "a,b", "a; b", or "a b" all yield the same list.
"""

import re

_SEPARATORS = re.compile(r"[,;\s]+")


def parse_package_names(raw_value):
    """Split a LOCAL_TESTED_PACKAGES_NAMES value into package names on commas, semicolons, or whitespace."""
    if not raw_value:
        return []
    return [name for name in _SEPARATORS.split(raw_value.strip()) if name]
