###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Prints a formatted build configuration summary table from Yamato environment variables.
Emitted after the sample is cloned and unity-downloader-cli is installed, but before the slow editor
download, so the configuration is visible early in the Yamato log while still being able to resolve the
editor actually used by the build.
"""

import argparse
import os
import platform
import re
import subprocess

from package_parsing import parse_package_names

SEP = "=" * 72
PLATFORM_MAC = "mac"
ENV_SCRIPTING_BACKEND = "SCRIPTING_BACKEND_(IL2CPP_MONO_CORECLR)"
ENV_PLATFORM = "PLATFORM_(WIN64_MAC_ANDROID)"
ENV_SAMPLE_BRANCH = "SAMPLE_BRANCH"
ENV_UNITY_VERSION = "UNITY_VERSION"
ENV_LOCAL_TESTED_PACKAGES_NAMES = "LOCAL_TESTED_PACKAGES_NAMES"
ENV_GIT_BRANCH = "GIT_BRANCH"

# Friendly labels for the build agent OS the job ran on (the value passed by --build-machine-os).
BUILD_MACHINE_DISPLAY = {"windows": "Windows"}

# Length to truncate a full Git revision to, matching the form ProjectVersion.txt records (e.g.
# "6000.5.0a5 (4928cd185deb)").
SHORT_REVISION_LENGTH = 12


def run_git(source_dir, *args, check=False):
    try:
        result = subprocess.run(
            ["git", "-C", source_dir, *args],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=check,
        )
        return result.stdout.strip() if result.stdout else ""
    except Exception:
        return ""


def get_package_branch_info():
    source_dir = os.environ.get("YAMATO_SOURCE_DIR", ".")
    # Yamato checks the source out at a detached HEAD, so git can't report the branch; GIT_BRANCH carries the
    # branch the job runs against (the PR source branch for PR-triggered jobs).
    branch = os.environ.get(ENV_GIT_BRANCH, "").strip()
    commit = run_git(source_dir, "rev-parse", "--short", "HEAD")
    if branch and commit:
        return f"{branch} ({commit})"
    if branch:
        return branch
    if commit:
        return f"<unknown branch> ({commit})"
    return "N/A"


def get_sample_branch_commit(sample_repo_url, sample_branch):
    try:
        result = subprocess.run(
            ["git", "ls-remote", sample_repo_url, f"refs/heads/{sample_branch}"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            full_sha = result.stdout.strip().split()[0]
            return full_sha[:10]
    except Exception:
        pass
    return None


def get_editor_version_from_downloader(unity_version):
    try:
        # --fast resolves branch-style versions (e.g. "trunk") against cached builds; --wait falls back to a
        # pending build when none is cached, so resolution does not flake. Mirrors the download/validate calls.
        result = subprocess.run(
            ["unity-downloader-cli", "--fast", "--wait", "-u", unity_version, "-c", "editor", "--skip-download"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False,
        )
        combined = result.stderr + result.stdout
        match = re.search(r"Grabbing unity release (\S+) which is revision: (\w+)", combined)
        if match:
            return f"{match.group(1)} ({match.group(2)})"
        version_match = re.search(r"Version:\s*(\S+)", result.stderr)
        sha = result.stdout.strip()
        if version_match:
            return f"{version_match.group(1)}{f' ({sha[:SHORT_REVISION_LENGTH]})' if sha else ''}"
    except Exception:
        pass
    return unity_version


def get_editor_version_from_project(project_path):
    """Read the editor the cloned sample was authored with, preferring the version+revision form."""
    try:
        version_file = os.path.join(project_path, "ProjectSettings", "ProjectVersion.txt")
        with open(version_file, "r", encoding="utf-8") as f:
            content = f.read()
        # e.g. "m_EditorVersionWithRevision: 6000.5.0a5 (4928cd185deb)"
        match = re.search(r"^m_EditorVersionWithRevision:\s*(.+?)\s*$", content, re.MULTILINE)
        if match:
            return match.group(1).strip()
        match = re.search(r"^m_EditorVersion:\s*(\S+)\s*$", content, re.MULTILINE)
        if match:
            return match.group(1)
    except Exception:
        pass
    return "N/A"


def get_updated_editor():
    """Resolve the editor actually used by the build, as opposed to the one the sample was authored with."""
    unity_version = os.environ.get(ENV_UNITY_VERSION)
    if unity_version:
        return get_editor_version_from_downloader(unity_version)
    return None


def print_mac_on_windows_note(target_platform):
    """
    A macOS player cross-compiled on a Windows agent loses its executable bit and carries a quarantine
    attribute, so the .app may refuse to open on the Mac. Surface the recovery commands in the job log
    when (and only when) a mac build is produced on a Windows host.
    """
    if target_platform.strip().lower() != PLATFORM_MAC or platform.system() != "Windows":
        return

    lines = [
        "",
        SEP,
        "  Note for Mac users (mac build produced on a Windows agent)",
        SEP,
        "  If you are unable to open the build, run the following on the Mac:",
        "    xattr -c <path/to/application.app>",
        "    chmod -R +x <path/to/application.app>",
        SEP,
        "",
    ]
    print("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description="Print build configuration summary.")
    parser.add_argument("--project-name", required=True, help="Project key used in CI.")
    parser.add_argument(
        "--sample-repo-url",
        help="GitHub URL of sample repo, used to resolve sample branch commit.",
    )
    parser.add_argument(
        "--project-path",
        help="Path to the cloned Unity project root, used to read the sample's editor from ProjectVersion.txt.",
    )
    parser.add_argument(
        "--build-machine-os",
        choices=sorted(BUILD_MACHINE_DISPLAY.keys()),
        help="OS of the build agent the job ran on; shown in the summary.",
    )
    args = parser.parse_args()

    rows = [("Project Name", args.project_name)]

    # Editor the sample was authored with vs. the editor the build actually uses.
    original_editor = get_editor_version_from_project(args.project_path) if args.project_path else None
    updated_editor = get_updated_editor()

    git_package_branch = get_package_branch_info()

    # The package under test is the job's own source checkout, so report its branch.
    rows.append(("Package Branch", git_package_branch))

    # SAMPLE_BRANCH env var holds the external project branch.
    sample_branch = os.environ.get(ENV_SAMPLE_BRANCH, "").strip()
    if sample_branch:
        commit = get_sample_branch_commit(args.sample_repo_url, sample_branch) if args.sample_repo_url else None
        branch_display = f"{sample_branch} ({commit})" if commit else sample_branch
    else:
        branch_display = f"<empty> resolved to {git_package_branch}"
    rows.append(("Sample Branch", branch_display))

    # Lead with the editor the build uses; note the project's authored editor (ProjectVersion.txt) when known.
    project_editor = original_editor if original_editor and original_editor != "N/A" else None
    if updated_editor and project_editor:
        editor_display = f"{updated_editor}  (project's ProjectVersion.txt: {project_editor})"
    else:
        editor_display = updated_editor or original_editor
    if editor_display:
        rows.append(("Editor Version", editor_display))

    local_tested_packages = parse_package_names(os.environ.get(ENV_LOCAL_TESTED_PACKAGES_NAMES, ""))
    if local_tested_packages:
        rows.append(("Local Tested Packages", ", ".join(local_tested_packages)))

    rows.append(("Scripting Backend", os.environ.get(ENV_SCRIPTING_BACKEND, "N/A")))

    target_platform = os.environ.get(ENV_PLATFORM, "N/A")
    rows.append(("Target Platform", target_platform))

    # The agent OS the build ran on, distinct from the target platform (a Windows agent can cross-build a mac
    # player). Best-effort: only shown when the recipe passed --build-machine-os.
    if args.build_machine_os:
        rows.append(("Build Machine", BUILD_MACHINE_DISPLAY[args.build_machine_os]))

    label_width = max(len(label) for label, _ in rows)
    lines = ["", SEP, "  Build Configuration Summary", SEP]
    for label, value in rows:
        lines.append(f"  {label:<{label_width}}  :  {value}")
    lines += [SEP, ""]

    print("\n".join(lines))

    print_mac_on_windows_note(target_platform)


if __name__ == "__main__":
    main()
