###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Extends a sparse-checked-out sample clone to include the repo-relative package folders it
references via UPM `file:` dependencies.

A sample project is cloned with a blob-less partial clone whose working tree is restricted to
<project-path> (see CloneProject). The project's <project-path>/Packages/manifest.json can list
`file:` dependencies whose paths (relative to the manifest's own Packages/ directory) resolve to
folders OUTSIDE <project-path> -- for example NetcodeSamples references the repo-root Packages/
folder via "file:../../../Packages/com.unity.entities". Those folders are never materialized by the
initial sparse checkout, so UPM cannot resolve the packages and the build fails.

This script parses the cloned manifest, resolves each `file:` reference to a repo-relative
directory, and `git sparse-checkout add`s the ones that fall outside <project-path>. References that
escape the repository root, that already live inside <project-path>, or a missing manifest are
skipped without failing the build.

A single pass is sufficient -- no recursion is needed. The sample author lists every repo-local
sibling package as a `file:` reference in the PROJECT manifest (NetcodeSamples lists
entities/transport/netcode/URP there). A pulled-in package's own package.json declares its
dependencies as registry version refs, not `file:` references into the monorepo, so transitive
dependencies resolve from the package registry rather than via repo-local paths.

This must run BEFORE manifest_update.py: that script rewrites the tested packages to
`file:%YAMATO_SOURCE_DIR%/...` refs pointing at the source checkout (not the sample repo), so the
resolver must see the sample's ORIGINAL manifest and act only on the sample repo's own internal refs.
"""

import argparse
import json
import posixpath
import subprocess
import sys

SEPARATOR = "=" * 80


def parse_args():
    parser = argparse.ArgumentParser(
        description="Add repo-relative file: package folders to a sample clone's sparse checkout."
    )
    parser.add_argument("--cloned-root", required=True, help="Absolute path to the cloned sample repo (e.g. C:/ClonedProject).")
    parser.add_argument("--project-path", required=True, help="Repo-relative project path (e.g. Workspace/NetcodeSamples).")
    parser.add_argument("--branch", required=True, help="Branch to re-checkout so newly included blobs are fetched.")
    return parser.parse_args()


def resolve_reference(project_path, target):
    """
    Resolves a manifest `file:` target (relative to <project-path>/Packages) to a repo-relative,
    forward-slash directory. Returns one of:
      ("escape", combined) -- the path escapes the repository root; warn and skip.
      ("inside", combined) -- the path is inside <project-path>; already checked out, skip.
      ("candidate", combined) -- a repo-relative dir outside <project-path>; add to the checkout.
    """
    combined = posixpath.normpath(posixpath.join(project_path + "/Packages", target))

    if combined == ".." or combined.startswith("../"):
        return "escape", combined
    if combined == project_path or combined.startswith(project_path + "/"):
        return "inside", combined
    return "candidate", combined


def collect_candidates(dependencies, project_path):
    candidates = []
    skipped_inside = []
    skipped_escape = []
    seen = set()

    for ref in dependencies.values():
        if not str(ref).startswith("file:"):
            continue

        target = str(ref)[len("file:"):]
        kind, combined = resolve_reference(project_path, target)
        if kind == "escape":
            skipped_escape.append(combined)
        elif kind == "inside":
            skipped_inside.append(combined)
        elif combined not in seen:
            seen.add(combined)
            candidates.append(combined)

    return candidates, skipped_inside, skipped_escape


def print_summary(candidates, skipped_inside, skipped_escape):
    print()
    print(SEPARATOR)
    print("SPARSE CHECKOUT FILE: REFERENCE RESOLUTION")
    print(SEPARATOR)
    print(f"Added (outside project):     {candidates if candidates else '<none>'}")
    print(f"Skipped (already in project): {skipped_inside if skipped_inside else '<none>'}")
    print(f"Skipped (escapes repo root):  {skipped_escape if skipped_escape else '<none>'}")
    print(SEPARATOR)
    print()


def main():
    args = parse_args()

    project_path = args.project_path.replace("\\", "/").strip("/")
    if not project_path or project_path == ".":
        print("[INFO] Project path is the repository root; no sparse checkout to extend.")
        return

    manifest_path = posixpath.join(args.cloned_root.replace("\\", "/"), project_path, "Packages/manifest.json")

    try:
        with open(manifest_path, "r", encoding="utf-8") as manifest_file:
            manifest_data = json.load(manifest_file)
    except FileNotFoundError:
        print(f"[INFO] No manifest at '{manifest_path}'; nothing to resolve.")
        return
    except Exception as error:
        print(f"Error reading manifest '{manifest_path}': {error}", file=sys.stderr)
        sys.exit(1)

    dependencies = manifest_data.get("dependencies", {})
    candidates, skipped_inside, skipped_escape = collect_candidates(dependencies, project_path)

    for escaped in skipped_escape:
        print(f"[WARN] file: reference resolves outside the repository root and was skipped: '{escaped}'", file=sys.stderr)

    if not candidates:
        print("[INFO] No external file: references to add to the sparse checkout.")
        print_summary(candidates, skipped_inside, skipped_escape)
        return

    add_result = subprocess.run(
        ["git", "-C", args.cloned_root, "sparse-checkout", "add", *candidates],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if add_result.returncode != 0:
        print(f"Error adding paths to sparse checkout: {add_result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)

    # The blob:none partial clone fetches the newly included blobs lazily on checkout, mirroring
    # CloneProject's final checkout (robust across git versions).
    checkout_result = subprocess.run(
        ["git", "-C", args.cloned_root, "checkout", args.branch],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if checkout_result.returncode != 0:
        print(f"Error checking out '{args.branch}' after extending sparse checkout: {checkout_result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)

    print_summary(candidates, skipped_inside, skipped_escape)


if __name__ == "__main__":
    main()
