###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Helper script that copies build scripts into the cloned Unity project to execute build action from within
"""

import argparse
import os
import shutil


def parse_args():
    parser = argparse.ArgumentParser(description="Set up build scripts in cloned project.")
    parser.add_argument("--project-path", required=True, help="Path to the cloned project root.")
    return parser.parse_args()


def main():
    args = parse_args()
    target_dir = os.path.join(args.project_path, "Assets", "CI", "Scripts", "Editor")
    # BuilderScripts.cs and the asmdef are materialized into this script's own directory, so resolve them
    # relative to __file__. This stays correct regardless of the consumer's configured ScriptsRelativeDir.
    source_dir = os.path.dirname(os.path.abspath(__file__))
    os.makedirs(target_dir, exist_ok=True)

    for filename in ["Unity.ProjectBuild.Editor.asmdef", "BuilderScripts.cs"]:
        source_path = os.path.join(source_dir, filename)
        target_path = os.path.join(target_dir, filename)
        shutil.copy(source_path, target_path)


if __name__ == "__main__":
    main()
