###############################################################################
### Auto-generated by RecipeEngine.Modules.BuildAutomation. DO NOT EDIT.    ###
### You may override this file locally, but any changes will be overwritten ###
### the next time CI is regenerated. Permanent fixes must be made inside:   ###
### RecipeEngine.Modules.BuildAutomation/EmbeddedScripts/                  ###
###############################################################################

"""
Validates Yamato environment variables based on predefined rules.
Checks always-required values and optional repo/feature-specific values.
Exits with non-zero status if validation fails, halting the build process early.
"""

import argparse
import os
import re
import subprocess
import sys

from package_parsing import parse_package_names

ENV_SCRIPTING_BACKEND = "SCRIPTING_BACKEND_(IL2CPP_MONO_CORECLR)"
ENV_PLATFORM = "PLATFORM_(WIN64_MAC_ANDROID)"
ENV_SAMPLE_BRANCH = "SAMPLE_BRANCH"
ENV_UNITY_VERSION = "UNITY_VERSION"
ENV_LOCAL_TESTED_PACKAGES_NAMES = "LOCAL_TESTED_PACKAGES_NAMES"

ALLOWED_SCRIPTING_BACKENDS = {"il2cpp", "mono", "coreclr"}
ALLOWED_PLATFORMS = {"win64", "mac", "android"}

CORECLR_BACKEND = "coreclr"
# coreclr is only a supported scripting backend from this editor onward; older editors must use il2cpp/mono.
MIN_CORECLR_EDITOR_VERSION = (6000, 6)
MIN_CORECLR_EDITOR_VERSION_DISPLAY = "6000.6"

BUILD_MACHINE_WINDOWS = "windows"
ALLOWED_BUILD_MACHINE_OS = {BUILD_MACHINE_WINDOWS}

# Platform/scripting-backend combinations that are invalid regardless of the build machine OS.
INVALID_COMBINATIONS = [
    (
        "android",
        "mono",
        "Android platform with mono is not supported. "
        "Mobile builds require the il2cpp or coreclr scripting backend.",
    ),
]

# Combinations that depend on which OS the build agent runs. il2cpp produces a native player, so a Windows
# IL2CPP player needs a Windows agent; a mac il2cpp player cannot be produced on the Windows agent (macOS
# agents are a planned follow-up).
INVALID_COMBINATIONS_BY_BUILD_MACHINE = {
    BUILD_MACHINE_WINDOWS: [
        (
            "mac",
            "il2cpp",
            "Mac il2cpp players cannot be built on a Windows agent. "
            "Use mono to cross-build mac on Windows.",
        ),
    ],
}


def validate_required_enum(var_name, allowed_values):
    value = os.environ.get(var_name, "").strip().lower()
    if not value:
        return [f"ERROR: Missing required environment variable: {var_name}"]

    if value not in allowed_values:
        return [
            f"ERROR: Invalid {var_name}: '{value}'. "
            f"Allowed values: {sorted(list(allowed_values))}"
        ]

    return []


def validate_core_variables():
    errors = []
    errors.extend(validate_required_enum(ENV_PLATFORM, ALLOWED_PLATFORMS))
    errors.extend(validate_required_enum(ENV_SCRIPTING_BACKEND, ALLOWED_SCRIPTING_BACKENDS))
    return errors


def parse_major_minor(version):
    """Parses the leading MAJOR.MINOR of a Unity version string (e.g. '6000.6.0a7' -> (6000, 6)).
    Returns None when the two leading numeric components cannot be determined."""
    parts = version.split(".")
    if len(parts) < 2:
        return None

    numbers = []
    for part in parts[:2]:
        match = re.match(r"\d+", part.strip())
        if not match:
            return None
        numbers.append(int(match.group()))
    return tuple(numbers)


def parse_version_tuple(version):
    """Extracts the leading numeric MAJOR[.MINOR[.PATCH]] of a Unity version string as a tuple, padding
    missing trailing components with 0 (e.g. '6000.5.0a5' -> (6000, 5, 0), '6000.6' -> (6000, 6, 0)).
    Returns None when no leading major number is present."""
    numbers = []
    for part in str(version).strip().split(".")[:3]:
        match = re.match(r"\d+", part.strip())
        if not match:
            break
        numbers.append(int(match.group()))

    if not numbers:
        return None

    while len(numbers) < 3:
        numbers.append(0)
    return tuple(numbers)


def parse_resolved_release(downloader_output):
    """Parses the editor version unity-downloader-cli reports it resolved to, from its combined output
    (e.g. 'Grabbing unity release 6000.5.0a5 which is revision: ...'). Returns None when not present."""
    match = re.search(r"Grabbing unity release (\S+)", downloader_output)
    return match.group(1) if match else None


def validate_min_supported_editor(unity_version, downloader_output, min_supported_editor):
    """Fails when the editor unity-downloader-cli actually resolved is older than the sample's minimum
    supported editor. Best-effort: if either version can't be parsed, warn and pass (the floor is advisory)."""
    resolved = parse_resolved_release(downloader_output)
    if not resolved:
        print(
            f"WARNING: could not determine the resolved editor version for {ENV_UNITY_VERSION} "
            f"'{unity_version}'; skipping the minimum supported editor check.",
            file=sys.stderr,
        )
        return []

    resolved_parsed = parse_version_tuple(resolved)
    min_parsed = parse_version_tuple(min_supported_editor)
    if resolved_parsed is None or min_parsed is None:
        print(
            f"WARNING: could not compare resolved editor '{resolved}' against minimum supported "
            f"'{min_supported_editor}'; skipping the minimum supported editor check.",
            file=sys.stderr,
        )
        return []

    if resolved_parsed < min_parsed:
        return [
            f"ERROR: resolved editor '{resolved}' (from {ENV_UNITY_VERSION} '{unity_version}') is older than "
            f"the sample's minimum supported editor '{min_supported_editor}'."
        ]
    return []


def coreclr_editor_error(editor_major_minor, editor_display):
    """Returns an error when the coreclr backend is selected but the given editor MAJOR.MINOR is older than the
    minimum. `editor_major_minor` is a (major, minor) tuple, or None to skip (undeterminable version)."""
    scripting_backend = os.environ.get(ENV_SCRIPTING_BACKEND, "").strip().lower()
    if scripting_backend != CORECLR_BACKEND or editor_major_minor is None:
        return []

    if editor_major_minor < MIN_CORECLR_EDITOR_VERSION:
        return [
            f"ERROR: coreclr scripting backend requires editor "
            f"{MIN_CORECLR_EDITOR_VERSION_DISPLAY} or newer, but the editor is '{editor_display}'."
        ]
    return []


def validate_coreclr_editor_version():
    """coreclr is only supported from editor 6000.6 onward. Checked here against the *requested* UNITY_VERSION
    when it is a concrete MAJOR.MINOR; branch-style values (e.g. "trunk", "6000.6/staging") can't be judged from
    the env text, so they are deferred to the resolved-editor check in validate_unity_version. Skipped when
    UNITY_VERSION is absent."""
    scripting_backend = os.environ.get(ENV_SCRIPTING_BACKEND, "").strip().lower()
    if scripting_backend != CORECLR_BACKEND:
        return []

    unity_version = os.environ.get(ENV_UNITY_VERSION, "").strip()
    if not unity_version:
        return []

    parsed = parse_major_minor(unity_version)
    if parsed is None:
        # Branch-style version: the resolved-editor coreclr check in validate_unity_version handles it.
        return []

    return coreclr_editor_error(parsed, unity_version)


def validate_combinations(build_machine_os):
    errors = []
    platform = os.environ.get(ENV_PLATFORM, "").strip().lower()
    scripting_backend = os.environ.get(ENV_SCRIPTING_BACKEND, "").strip().lower()

    combinations = INVALID_COMBINATIONS + INVALID_COMBINATIONS_BY_BUILD_MACHINE.get(build_machine_os, [])
    for invalid_platform, invalid_backend, message in combinations:
        if platform == invalid_platform and scripting_backend == invalid_backend:
            errors.append(f"ERROR: Invalid Configuration: {message}")
    return errors


def validate_sample_branch(github_repo_url):
    errors = []
    sample_branch = os.environ.get(ENV_SAMPLE_BRANCH, "").strip()
    if not sample_branch:
        return [f"ERROR: Missing required environment variable: {ENV_SAMPLE_BRANCH}"]

    result = subprocess.run(
        ["git", "ls-remote", "--heads", "--exit-code", github_repo_url, sample_branch],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        errors.append(
            f"ERROR: Branch '{sample_branch}' was not found in repository '{github_repo_url}'."
        )
    return errors


def validate_unity_version(min_supported_editor=None):
    errors = []
    unity_version = os.environ.get(ENV_UNITY_VERSION, "").strip()
    if not unity_version:
        return [f"ERROR: Missing required environment variable: {ENV_UNITY_VERSION}"]

    try:
        # --fast resolves branch-style versions (e.g. "trunk", "6000.6/staging") against already-cached builds;
        # --wait is required alongside it because --fast alone exits non-zero when nothing is cached yet (trunk
        # builds expire), which would spuriously reject a valid branch. Mirrors the download invocation
        # (--fast --wait). --skip-download still resolves and prints the revision without fetching the editor.
        result = subprocess.run(
            ["unity-downloader-cli", "--fast", "--wait", "-u", unity_version, "-c", "editor", "--skip-download"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        return [
            "ERROR: unity-downloader-cli is not installed; "
            f"cannot validate {ENV_UNITY_VERSION}. Install it before running this check."
        ]
    if result.returncode != 0:
        errors.append(
            f"ERROR: unity-downloader-cli does not recognize {ENV_UNITY_VERSION} '{unity_version}'."
        )
        return errors

    resolved_revision = result.stdout.strip()
    if not resolved_revision:
        errors.append(
            "ERROR: unity-downloader-cli did not return a resolved revision for "
            f"{ENV_UNITY_VERSION} '{unity_version}'."
        )

    combined_output = result.stderr + result.stdout

    # coreclr floor against the RESOLVED editor, so branch-style versions (e.g. "trunk", "6000.6/staging") that
    # the raw env text can't reveal are still gated once the downloader resolves them.
    resolved_release = parse_resolved_release(combined_output)
    if resolved_release:
        errors.extend(coreclr_editor_error(parse_major_minor(resolved_release), resolved_release))

    if min_supported_editor:
        errors.extend(
            validate_min_supported_editor(unity_version, combined_output, min_supported_editor)
        )
    return errors


def validate_local_tested_packages(base_path):
    package_names = parse_package_names(os.environ.get(ENV_LOCAL_TESTED_PACKAGES_NAMES, ""))
    errors = []

    # Clearing the variable at trigger time opts out of substitution (plain build); nothing to validate.
    if not package_names:
        return []

    for package_name in package_names:
        package_dir = os.path.join(base_path, package_name)
        package_json = os.path.join(package_dir, "package.json")

        if not os.path.isdir(package_dir):
            errors.append(
                f"ERROR: Local tested package directory does not exist: '{package_dir}'"
            )
            continue

        if not os.path.isfile(package_json):
            errors.append(
                f"ERROR: package.json was not found for local tested package '{package_name}' "
                f"at '{package_json}'"
            )

    if errors:
        errors.append(
            f"HINT: {ENV_LOCAL_TESTED_PACKAGES_NAMES} was parsed as {package_names}. Separate package names "
            "with a comma, semicolon, or space (e.g. 'com.unity.netcode,com.unity.entities'); each must be a "
            f"folder under '{base_path}' that contains a package.json."
        )

    return errors


def parse_args():
    parser = argparse.ArgumentParser(description="Validate Yamato variables for build automation.")
    parser.add_argument(
        "--check-sample-branch",
        dest="sample_branch_repo_url",
        help="Validate that SAMPLE_BRANCH exists in this repository URL.",
    )
    parser.add_argument(
        "--check-unity-version",
        action="store_true",
        help="Validate UNITY_VERSION by resolving it through unity-downloader-cli.",
    )
    parser.add_argument(
        "--check-local-tested-packages",
        dest="local_tested_packages_path",
        help="Validate LOCAL_TESTED_PACKAGES_NAMES under this base package path.",
    )
    parser.add_argument(
        "--min-supported-editor",
        dest="min_supported_editor",
        help="Sample's minimum supported editor; the editor resolved for UNITY_VERSION must be at least "
        "this version (checked only with --check-unity-version).",
    )
    parser.add_argument(
        "--build-machine-os",
        choices=sorted(ALLOWED_BUILD_MACHINE_OS),
        default=BUILD_MACHINE_WINDOWS,
        help="OS of the build agent; gates platform/scripting-backend combinations (e.g. mac+il2cpp).",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    errors = []
    errors.extend(validate_core_variables())
    errors.extend(validate_combinations(args.build_machine_os))
    errors.extend(validate_coreclr_editor_version())

    if args.sample_branch_repo_url:
        errors.extend(validate_sample_branch(args.sample_branch_repo_url))

    if args.check_unity_version:
        errors.extend(validate_unity_version(args.min_supported_editor))

    if args.local_tested_packages_path:
        errors.extend(validate_local_tested_packages(args.local_tested_packages_path))

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        print("\nOne or more parameters failed validation. Halting build.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
