blank_issues_enabled: False
contact_links:
  - name: Documentation Issues
    url: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/issues
    about: Create a documentation issue in our docs repository
  - name: Discord Community
    url: https://discord.gg/buMxnnPvTb
    about: Join our Discord community for questions, support and discussions
  - name: Unity Multiplayer Forum
    url: https://forum.unity.com/forums/multiplayer.26/
    about: Create a thread in the Unity Multiplayer Forum
  - name: Support
    url: https://discussions.unity.com/tag/netcode-for-gameobjects
    about: Creating a thread in discussions is usually the fastest way to get help from Unity stuff or other experienced users
  - name: Feedback
    url: https://discussions.unity.com/tag/netcode-for-gameobjects
    about: We are always looking for feedback on our products, so please let us know what you think