# Check based on https://github.com/marketplace/actions/allcheckspassed to prevent PRs from merging when there is no required checks but some jobs are running

name: All checks pass verification
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  allchecks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@v1
        with:
          delay: '0'
          retries: '100'
          polling_interval: '3'