name: Update issue labels

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

# Define labels here
env:
  AWAITING_RESPONSE: stat:awaiting response

jobs:
  auto_label:
    name: Calculate and update issue labels
    if: ${{ !github.event.issue.pull_request  }} && ${{ github.event.issue.state == 'open' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Calculate labels
        run: |
          ADD_LABELS=()
          REMOVE_LABELS=()

          if [[ "${{ github.event.comment.author_association }}" == "MEMBER" ]]; then
            ADD_LABELS+="${{ env.AWAITING_RESPONSE}}"
          else
            REMOVE_LABELS+="${{ env.AWAITING_RESPONSE}}"
          fi


          # Add further label logic here - uses bash

          echo "ADD_LABELS=$(IFS=,; echo "${ADD_LABELS[*]}")" >> $GITHUB_ENV
          echo "REMOVE_LABELS=$(IFS=,; echo "${REMOVE_LABELS[*]}")" >> $GITHUB_ENV

      - name: Update labels
        run: gh issue edit "$NUMBER" --add-label "$ADD_LABELS" --remove-label "$REMOVE_LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
