# GitHub Actions workflow to monitor Yamato CI job state on pull requests
# We are using https://cli.github.com/manual/gh_pr_checks
# The aim is to ensure that conditionally triggered Yamato jobs are completed successfully before allowing merges

# This job will be required in branch protection rules for develop, develop-2.0.0, and release/* branches. It's only goal will be to ensure that Yamato jobs are completed successfully before allowing Pr to merge.
# Note that conditional jobs will have 30s to show which is always the cas since they are showing up as soon as in distribution stage.

name: Yamato PR Supervisor

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - develop-2.0.0
      - release/*

jobs:
  yamato-supervisor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Wait and Verify Yamato Job Status
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sleep 30 
          gh pr checks ${{ github.event.pull_request.number }} --watch --fail-fast --interval 60